CREATE DATABASE IF NOT EXISTS ventas_jugos;

CREATE SCHEMA IF NOT EXISTS ventas_jugos2 DEFAULT
CHARSET UTF32;

DROP DATABASE ventas_jugos2;

USE ventas_jugos;

CREATE TABLE tb_vendedor (
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) NULL,
BARRIO VARCHAR(50) NULL,
COMISION FLOAT NULL,
FECHA_ADMISION DATE NULL,
DE_VACACIONES BIT(1) NULL, 
PRIMARY KEY(MATRICULA)
); /*Importante destacar que la primary key NO puede ser nula*/

CREATE TABLE tb_producto(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANO VARCHAR(50) NULL,
ENVASE VARCHAR(50) NULL,
PRECIO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE tb_cliente (
DNI varchar(11) NOT NULL,
NOMBRE varchar(100) DEFAULT NULL,
DIRECCION varchar(150) DEFAULT NULL,
BARRIO varchar(50) DEFAULT NULL,
CIUDAD varchar(50) DEFAULT NULL,
ESTADO varchar(45) DEFAULT NULL,
CP varchar(8) DEFAULT NULL,
FECHA_NACIMIENTO date DEFAULT NULL,
EDAD int(2) DEFAULT NULL,
SEXO varchar(1) DEFAULT NULL,
LIMITE_CREDITO float DEFAULT NULL,
VOLUMEN_COMPRA float DEFAULT NULL,
PRIMERA_COMPRA bit(1) DEFAULT NULL,
PRIMARY KEY (DNI)
); /*DEFAULT NULL significa que por defecto el campo va a ser nulo si este no se completa*/

DROP TABLE facturas;

CREATE TABLE tb_venta(
NUMERO VARCHAR(5) NOT NULL,
FECHA DATE NULL,
DNI VARCHAR(10) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT,
PRIMARY KEY (NUMERO)
);

CREATE TABLE items_facturas(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
CANTIDAD INT,
PRECIO FLOAT,
PRIMARY KEY (NUMERO,CODIGO)
);

/*Cambiando nombre a las tablas*/
ALTER TABLE tb_factura RENAME tb_venta; 
ALTER TABLE facturas RENAME tb_factura;
ALTER TABLE items_facturas RENAME tb_items_facturas;

DROP TABLE tb_items_facturas;

/*Agregando FK*/
ALTER TABLE tb_factura ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (DNI) REFERENCES tb_cliente(DNI);

ALTER TABLE tb_factura ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES tb_vendedor(MATRICULA);

ALTER TABLE tb_items_facturas ADD CONSTRAINT FK_PRODUCTO
FOREIGN KEY (CODIGO) REFERENCES tb_producto(CODIGO);

ALTER TABLE tb_items_facturas ADD CONSTRAINT FK_FACTURAS
FOREIGN KEY (NUMERO) REFERENCES tb_factura(NUMERO);

/*Luego creamos el diagrama y desde el diagrama exportamos el .sql que genera las tablas.*/