/* Comando HAVING */

/*Es un filtro que se aplica sobre el resultado de una agregación*/
SELECT X, SUM(Y) FROM tb GROUP BY X;
SELECT X, SUM(Y) FROM tb GROUP BY X HAVING SUM(Y) > 4;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabla_de_clientes GROUP BY ESTADO HAVING LIMITE_TOTAL > 300000;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO, MIN(PRECIO_DE_LISTA) AS PRECIO_MINIMO, SUM(PRECIO_DE_LISTA) AS SUMA_PRECIO 
FROM tabla_de_productos GROUP BY ENVASE HAVING SUM(PRECIO_DE_LISTA) >= 80 AND MAX(PRECIO_DE_LISTA) >= 5;