USE jugos;

CREATE TABLE TABLA_DE_VENDEDORES (
MATRICULA VARCHAR(5),
NOMBRE VARCHAR(100),
PORCENTAJE_COMISION FLOAT);

INSERT INTO TABLA_DE_VENDEDORES
(MATRICULA, NOMBRE, PORCENTAJE_COMISION)
VALUES
('00233', 'Joan Geraldo de la Fonseca', 0.10);

INSERT INTO TABLA_DE_VENDEDORES
(MATRICULA, NOMBRE, PORCENTAJE_COMISION)
VALUES
 ('00235','Márcio Almeida Silva',0.08);

INSERT INTO TABLA_DE_VENDEDORES
(MATRICULA, NOMBRE, PORCENTAJE_COMISION)
VALUES
('00236','Cláudia Morais',0.08);

UPDATE TABLA_DE_VENDEDORES SET PORCENTAJE_COMISION = 0.11
WHERE MATRICULA = '00236';

UPDATE TABLA_DE_VENDEDORES SET NOMBRE = 'Joan Geraldo de la Fonseca Junior'
WHERE MATRICULA = '00233';

DELETE FROM TABLA_DE_VENDEDORES WHERE MATRICULA = '00233';

ALTER TABLE TABLA_DE_VENDEDORES ADD COLUMN(FECHA_ADMISION DATE);
ALTER TABLE TABLA_DE_VENDEDORES ADD COLUMN(DE_VACACIONES BIT(1));
ALTER TABLE TABLA_DE_VENDEDORES ADD PRIMARY KEY (MATRICULA);

UPDATE TABLA_DE_VENDEDORES SET FECHA_ADMISION = '2014-08-15', DE_VACACIONES = 0 WHERE MATRICULA = '00235';
UPDATE TABLA_DE_VENDEDORES SET FECHA_ADMISION = '2013-09-17', DE_VACACIONES = 1 WHERE MATRICULA = '00236';

INSERT INTO TABLA_DE_VENDEDORES
(MATRICULA, NOMBRE, FECHA_ADMISION, PORCENTAJE_COMISION, DE_VACACIONES) VALUES ('00238','Pericles Alves','2016-08-21',0.11,0);

SELECT * FROM TABLA_DE_VENDEDORES;

SELECT NOMBRE, MATRICULA FROM TABLA_DE_VENDEDORES;

SELECT * FROM TABLA_DE_VENDEDORES WHERE NOMBRE = 'Cláudia Morais';

SELECT * FROM TABLA_DE_VENDEDORES WHERE PORCENTAJE_COMISION > 0.10;

SELECT * FROM TABLA_DE_VENDEDORES WHERE YEAR(FECHA_ADMISION) >= 2016;

SELECT * FROM TABLA_DE_VENDEDORES WHERE DE_VACACIONES = 1 AND YEAR(FECHA_ADMISION) < 2016;

